##############################################################################
# Multi-project makefile rules
#

all:
	@echo
	@echo === Building for STM32F407-Discovery ===============================
	@make --no-print-directory -f ./make/stm32f407_discovery.make all
	@echo ====================================================================
	@echo

clean:
	@echo
	-@make --no-print-directory -f ./make/stm32f407_discovery.make clean
	@echo

#
##############################################################################
